[phases.setup]
nixPkgs = ["nodejs", "nodePackages.npm", "ffmpeg", "fontconfig"]

[phases.build]
cmds = [
  "npm install",
  "mkdir -p /usr/share/fonts/truetype/jameel",
  "cp 'Jameel Noori Nastaleeq Kasheeda - [UrduFonts.com].ttf' /usr/share/fonts/truetype/jameel/JameelNoori.ttf",
  "fc-cache -fv"
]

[start]
cmd = "node server.js"
[phases.build]
cmds = [
  "npm install",
  "mkdir -p /usr/share/fonts/truetype/jameel && cp JameelNoori.ttf /usr/share/fonts/truetype/jameel/ && fc-cache -fv"
]
